### ISSUE TITLE
Foundation, Spatial, and Information Resources

### ISSUE THREAD

**Issue by cportele** [opengeospatial/oapi_common#100]
This issue has been created as part of the [public review](https://www.ogc.org/standards/requests/203) and is based on [document 19-072](https://portal.ogc.org/files/91975). Foundation, Spatial, and Information Resources are defined in section 8.1.

While I understand the idea, I don't think that the separation into Foundation Resources, Spatial Resources, and Information Resources works. It will create more issues than it solves. Just one example (but there are many): a resource that does some kind of processing on data would be an "information resource" based on the "definitions" in 8.1.1. Really? My proposal is to drop the use of these terms. If there is a decision to keep them, add (better) definitions to the Terms and Definitions clause.

This is somewhat related to #99.

**Comment by jerstlouis** [comment]
I see a critical need for such a categorization of OGC API modules, but the "Processing" resources is definitely missing as its own category. I had suggested "auxiliary resources" rather than "information resources".

We may also revisit that list, e.g. I think we need "Space partitioning mechanisms" modules (e.g. Tiles, DGGS, BBOX/resolution). Another category might be "Transaction mechanisms".

**Comment by jeffharrison** [comment]
Clemens,

Thank you for posting this. I'm looking at the Resources categorization again and also wondering whether it would be simpler to indicate something like 'there are Resources' and leave it at that...

Best Regards,
Jeff

**Comment by joanma747** [comment]
Do we need to discuss about "static" and "dynamic"? The result of a process is a "dynamic resource". 
Resources are "things" that you can retrieve (in a representation). What is the representation returned by a process?. A process resource will return the description of the process (what it does and in's and out's). "Process" can be synonymous of "computations resources".

**Comment by joanma747** [comment]
I believe that since the dataset is not retrievable, everything that a OGC API returns is the result of some kind of processing. When you request a collection, the collection may be "created" for you in real time. We you ask for a route, a polyline is created for you. Difficult to separate both use cases. The existence of processes and processing chains is undeniable

It is also true that there are processes that la longer than others. In asynchronous process then you need the idea of a "job" as an intermediate resource. 

I vote for classifying the resources depending on they response (representation returned) and not on if they are data retrieval process or GIS analytics processes.

**Comment by jerstlouis** [comment]
@joanma747 My suggestion is to separate "Processes" vs. "Geospatial Data" (tentatively "Collections").

- Processes correspond to WPS and WMS (as a server-side renderer taking in some layers or styling options =), and most often take geospatial data as an input, and/or parameters (when no geospatial data is supplied, often it may use some built-in geospatial data which may or may not be exposed -- e.g. routing works on a roads network even if you only supply point A & B)

- Collections correspond to WFS and WCS, or WMS as a predefined fixed geospatial image which will has no capability of returning anything different.

All these collections (Features, Coverages, WMS Images Coverages (pixels)) can be retrieved tiled.

The input and output of processes can be transfered synchronously or asynchronously, and also tiled. Process execution can be done in a distributed manner when tiles are used (each tile can run on its own system / CPU or GPU core).

**Comment by jerstlouis** [comment]
The idea of a "virtual collection" is present the output of process with pre-defined inputs and parameters as a collections (i.e. having it as an entry in /collections/{virtualCollectionID}.

The only things that really make a "virtual collection" distinguishable from a "normal" is if the API exposes either:
A) A way to create a such a virtual collection (by supplying the process invocation document to create it, which specifies input collections and associafted paraeters, or other chained input processes and its own inputs and parametrs)

B) A way to retrieve the "source" process invocation document that created it. This could allow the client to tweak it and either use A) to add a modified version, or directly invoke the process with the tweaked version.

Virtual collections could also facilitate caching.
An example use case is users making maps out of a bunch of source layers, and when happy publishing the results as a virtual collection. Whenever the source data gets updated, the maps and cache will all get updates automatically.

**Comment by jeffharrison** [comment]
Great discussions today.

The concept of a 'virtual collection' is very interesting. I look forward to discussing it further and possibly seeing examples.

I think 'virtual collections' may be a good topic in the new Collections standard.

On the topic of resources, and resource category breakdowns. It's almost inevitable that people will have differing opinions on this (it's like POIs, everybody has their favorites and they all think they are right ;-).

I would recommend the 'Core' portion of Common keep it simple. For example, saying something like, 'There are resources' and 'Resources may come in many Types'. 

Best Regards,
Jeff

**Comment by jerstlouis** [comment]
@jeffharrison It is true that the hard need to categorize and describe "Geospatial data" resources really starts in the "OGC API Common - Collections" part, because based on that description it can be determined whether it would be appropriate to implement Collections or not.

Similarly, categorizing and describing what are "Processing" ressources (https://en.wikipedia.org/wiki/Computational_resource as Gobe pointed out!) helps determine whether Processes should be implemented.

Just like you could serve a GeoJSON or GeoTIFF without implementing Collections, you could have a REST API that does some processing without having a Process description resource (not referring to the OpenAPI document itself here, which you also could or could not have).

But Collections facilitates discovering and accessing data, and Processes helps discovering processes, so these are great OGC API modules to implement!

Now the main reason to mention Collections (geospatial data) and Processes in OGC API - Common (Core) would be to introduce these concepts and raise awareness that these other modular blocks exist, and inform the readers about what they are and why they might care about those conformance classes, before referring them to those other documents.

**Comment by dblodgett-usgs** [comment]
I agree with @jeffharrison -- Common should describe the resources that are prescribed in common and not opine about the nature of resources beyond the common ones other than to say they will provide varied content and have varied behavior. If, in the future, we have a need for a taxonomy of resource types, that might make it to common, but I just don't think we have the foresight to get that right at this phase.

**Comment by cmheazel** [comment]
Spatial and Information Resources have been removed from Core.  They are defined in Collections where they may still have some use.  Also added Temporal Resources to align with the Temporal Thing concept.

**Comment by joanma747** [comment]
Core does not discuss about resource types at all. It introduces the concept of common resource (formerly known foundational) that includes the 3 defined.

Do we need a definition about foundational resource?
[foundation-resources-definition]]
* *Foundation Resources* +
resources which are provided by every OGC API to help clients to understand the offerings and capabilities of that API.

The proposed definition is
* *Common Resources* +
resources defined in "OGC API - Common - Part 1: Core" namely landing page, conformance declaration and API definition

We will rename "foundational resources" to "common resource".

**Comment by jerstlouis** [comment]
@joanma747
Wouldn't additional Common parts also define "Common" resources, which could also be used by different modular blocks?

Why not call them "Core" resources, since they are defined by Part1: Core?

**Comment by cmheazel** [comment]
See if the whole concept of Foundation resources can be dropped from the Standard.

**Comment by cmheazel** [comment]
The concept of Foundation resources has been purged.
Recommended to be closed.
