### ISSUE TITLE
Use of "Each OGC API ..."

### ISSUE THREAD

**Issue by cportele** [opengeospatial/oapi_common#103]
This issue has been created as part of the [public review](https://www.ogc.org/standards/requests/203) and is based on [document 19-072](https://portal.ogc.org/files/91975). See in particular section 8.2.1. 

The document uses "Each OGC API ...". There is not such thing as "an OGC API", there are only "OGC API standards" and Web APIs conforming to them. This should be rephrased.

**Comment by bradh** [comment]
I think this is standards lawyering. Just define the concept before first use, then keep the existing wording.

Otherwise you'll be "Standards conformant (base and selected profiles) implementations of OGC APIs that conform to this OGC API Common (blah, whatever the agreed name it) and the OGC API Standards that invoke this standard, or other API Standards that may later choose to invoke this standard..." or something equally ridiculous,  as the start of most clauses, which will be unreadable.

**Comment by cportele** [comment]
When we coined the "OGC API" prefix one year ago it was one of the concerns that there would be an assumption that there would be something like an "OGC API". We shouldn't support such assumptions, in particular in Common.

In this case it can also be fixed easily by changing it to "Each API ...".

**Comment by dblodgett-usgs** [comment]
I agree with the proposal @cportele -- getting comfortable with the wording "Each OGC API..." will encourage the uninitiated to form a perspective of what OGC API is that we don't intend. Your suggestion is sufficiently general to not go down the "standards lawyering" [I call snark @bradh] road.

**Comment by cmheazel** [comment]
The latest update has attempted to use the term OGC Web API Standards when referring to the standards as a group and OGC API - {name} Standard when referring to a specific standard.  An implementation of an OGC Web API Standard is identified as such.
However, I doubt that I caught them all.

**Comment by cportele** [comment]
@cmheazel - The comment was not about referencing the OGC API standards (which you commented on), but about referencing a Web API that is implementing one or more OGC API standards.

**Comment by cmheazel** [comment]
Implemented the change recommended by @cportele . In section 8.1 of API-Common Core, the phrase "Each OGC API has --" has been changed to "Each API has --".
