### ISSUE TITLE
Core vs. Simple

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/oapi_common#12]
WFS 3.0 core was intended to be the minimal implementation of WFS 3.0.  For this to be true, there should be few if any restrictions.  What is not prohibited is allowed.  Is OAPI common consistent with this view?

**Comment by percivall** [comment]
An example of this was discussed in the 20190320 Common telecon for collections hierarchy.
Approach 1 "Simple Core": Core allows only Features in Collection.  Collections in collections would be defined in  an Extension.
Approach 2 "Simple Extension": Core allows Collections that can be Features and/or Collections.  Simple Profile would be to restrict this to Collection only includes Features.

**Comment by percivall** [comment]
Core could be "simple as in restricted" or Core could be "simple as in sublime or transcendent".

A Sublime Core expresses powerful concepts in simple language:
- Collections may include collections and features 
- CRS may be of any identified type 
- Domains may be 4D

Profiles can be extensions or constraints of Core:
- Profiles Constrain: 
        "collections shall not include collections," 
         "only one CRS is allowed," 
         "domain is restricted to 2D"
- Profiles Extend: by adding extra features, i.e., "bells and whistles"

A good, i.e., simple and extensible, approach would be:
"Sublime Core" with both "Simple Profiles" based on restrictions; and "Complex Profiles" with extensions.

**Comment by cportele** [comment]
This would work, getting the "Sublime Core" right might be a challenge though.

If we follow this approach then profiles should not follow the straightforward Modular Specifications approach and simply reference the Core conformance class(es) and add the profiling constraints in additional requirements. This would require that readers of a simple profile would have to understand the complete "Sublime Core" and we should avoid this.

Instead Simple Profiles should be allowed to define their requirements from scratch in a way that is consistent with the "Sublime Core" so that those interested in just the profile do not have to read and understand the full picture. In the Features case this would imply that we would leave the structure as it currently is.

The "Sublime Core" would mainly be a mechanism for us to document the common API concepts.

**Comment by cmheazel** [comment]
Given the positive vote for API-Features we can consider this issue closed.
