### ISSUE TITLE
Confusing use of requirements folder to do recommendations

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/oapi_common#18]
Some things in the requirements folder are requirements but others are recommendations. Examples:
https://github.com/opengeospatial/oapi_common/blob/master/OAPI-Common/requirements/core/PER_additional-status-codes.adoc
https://github.com/opengeospatial/oapi_common/blob/master/OAPI-Common/requirements/core/REC_cross-origin.adoc
I find this very confusing. IMHO, only requirements should be there.

**Comment by cmheazel** [comment]
Agree. I'll clean it up.

**Comment by joanma747** [comment]
Please, move the text to the document. some recommendations are very informative,even if they should not be considered requirements.

**Comment by cportele** [comment]
I did this in WFS because the template does not have folders for recommendations or permissions. So maybe clarify first with the DocTeam how to handle these cases and also update the standards template?

https://github.com/opengeospatial/templates/tree/master/standard_template/standard

I think it still makes sense to have recommendations and permissions separate, so that all normative statements are easier to identify (I assume this is the idea behind moving requirements to separate files).

**Comment by cmheazel** [comment]
Another approach, I'll move recommendations to a separate recommendation folder. Maybe make a few changes to the look and feel so they stand out from requirements.

**Comment by joanma747** [comment]
I like the proposed solution.

**Comment by cmheazel** [comment]
All Permissions and Recommendations are in the recommendations folder.  I'll visit potential formatting changes at a latter date.

**Comment by cmheazel** [comment]
In review 20 days without comment.  Closed
