### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/oapi_common#56]
From the API Hackathon ER

NGA comment: 
Consider requiring XML syntax for HTML [https://www.w3.org/TR/html5/introduction.html#html-vsxhtml] for HTML conformance, which implies all HTML documents are well-formed.
◦ makes the document more machine-friendly without sacrificing human-readability
◦ makes the document easier to consume for dynamic/generic clients using widely available
XML libraries instead of more lax, HTML-specific libraries with HTML’s specific parsing
requirements
◦ facilitates HTTP/1.1 agent-driven negotiation for non-user-facing clients whose initial
request to a service returns an HTML response
◦ enables the use of XPath and XSLT on HTML documents

**Comment by joanma747** [comment]
I had the impression that XHTML was dead and HTML5 was the future.
" When the time came to devise a new standard, the W3C (World Wide Web Consortium) decided to support HTML5 rather than XHTML 2."

https://www.dummies.com/web-design-development/html/the-relationship-between-html5-and-xhtml/

I do not thing we should support XHTML and at the same time more from XML to JSON encodings. Is not that a contradiction?
