### ISSUE TITLE
Link relation types in OGC API standards

### ISSUE THREAD

**Issue by cportele** [opengeospatial/oapi_common#76]
In OGC API Features we have re-used existing link relation types where we have found a match, but for three types we did not find a match and defined new ones ("conformance", "items" and "data").

See [OGC API - Features - Part 1: Core, 5.2. Link relations](http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_link_relations).

Since we now have a published spec, which is a pre-requisite for getting something into the IANA registry, I have discussed these types with the gatekeepers of the registry.

The feedback was that the terms are defined for specific applications but at the same time use very generic terms. They avoid including such terms, even if the definition is broad and not specific to the application context as "people tend to assume that being defined as part of a narrow specification (like OGC) restricts them to that use". 

Fair enough. Based on the discussion, it looks as if there are three ways forward for link relation types in OGC API:

1. We define the additional link relation types not as part of the OGC API standards, but in a general spec that gets reviewed by the wider Web community (IETF RFC, W3C Rec).
2. We use terms for "our" additional link relation types that put them in the specific application context (e.g. "ogc-conformance", etc.).
3. We continue to use generic terms and do not register them with IANA.

As you may guess, I am firmly against the third option, but I have still added it for completeness. Since OGC API is trying to integrate spatial data better into the rest of the Web and inventing our own hidden universe of link relation types would be counterproductive to that goal.

So, it would be good to have a discussion about the direction that we want to take with link relation types in OGC API in general. This is why I have created this as an issue here and not in OGC API Features.

The first option would be harder and more work than the second option. On the other hand, more general terms may be more useful in general and might see reuse in other applications outside of OGC API, too. This would help to make our links more understandable to others (without reading our specs).

There could also be a mix. That is, define link relation types that we think are of general use in an IETF/W3C spec and use a consistent OGC-specific naming strategy for others and continue to define those in the OGC API standards.

Any thoughts?

**Comment by p3dr0** [comment]
I recommend to consider the addition of the 'profile' link relation type to the section 5.2 list and analyse it as an alternative to the new relation "conforms" 

As a reminder this relation was used on the GML media type submitted to IANA  
https://www.iana.org/assignments/media-types/application/gml+xml

As a way forward for link relation types in OGC API I would be in favor of solution 1

**Comment by cportele** [comment]
> I recommend to consider the addition of the 'profile' link relation type to the section 5.2 list and analyse it as an alternative to the new relation "conforms"

"profile" is not an alternative to "conformance". In the conformance declaration resource we could have used "profile" links instead of just listing the conformance class URIs, but that ship has sailed I would say. As it is a very OGC API specific resource anyhow that only readers of the OGC API standards care about, I don't think this is an issue.

> As a way forward for link relation types in OGC API I would be in favor of solution 1

Yes, it would be the cleanest approach, but also requires much more work and effort to drive this through the process (in OGC plus IETF/W3C). Does "in favor" mean a commitment for an active role in this? Option 1 is only a real option in my view, if we have a small group that is committed and has the resources for doing it.

**Comment by p3dr0** [comment]
I'm concerned that outside OGC "conformance" and "profile" will have very similar readings and might originate a few problems (but that we can discuss in a separate issue)  

> Does "in favor" mean a commitment for an active role in this? Option 1 is only a real option in my view, if we have a small group that is committed and has the resources for doing it.

Yes, I'm available to support this effort

**Comment by m-mohr** [comment]
> The feedback was that the terms are defined for specific applications but at the same time use very generic terms. They avoid including such terms, even if the definition is broad and not specific to the application context as "people tend to assume that being defined as part of a narrow specification (like OGC) restricts them to that use".

Still, they already have Item:

> item: The target IRI points to a resource that is a member of the collection represented by the context IRI.

And defining Items in addition seems relatively straightforward:

>items: The target IRI points to a resource that is lists a subset or all members of the collection represented by the context IRI.

Agreed that data is probably the most general term one could think of and it's probably hard to describe.

> 1. We define the additional link relation types not as part of the OGC API standards, but in a general spec that gets reviewed by the wider Web community (IETF RFC, W3C Rec).

That sounds reasonable. Would this general RFC then be proposed to IANA? The question here is: When to do that? Wait for all OGC APIs to have their relation types defined? What happens afterwards for relation types defined in extensions or APIs defined after the RFC? Would this be open for external contributions from the wider Web community? For example, could we also add a relation type used in STAC (not sure whether there's one)?

> 2. We use terms for "our" additional link relation types that put them in the specific application context (e.g. "ogc-conformance", etc.).

I would avoid this as some of the relation types are also re-used outside of direct OGC specs (e.g. STAC and openEO) and then the OGC naming would leak into those contexts although the specifications are not really part of the OGC. Also, wouldn't this only work for a next iteration of OAF?

> 3. We continue to use generic terms and do not register them with IANA.

I'd also be fine with that. I always see the IANA list as open for proprietary extensions, because there's never all rel types pre-defined and at some point you need to invent your own. And some specifications not part of any standardization organization are just never entitled to register their rel types with IANA anyway.

**Comment by cportele** [comment]
I have also raised this with the OAB ([OAB Issue 1436](https://portal.opengeospatial.org/?m=projects&a=view&project_id=228&tab=5&act=details&issue_id=1436)).

**Comment by cmheazel** [comment]
Given the establishment of an OGC relation type registry, is this issue OBE?

**Comment by cportele** [comment]
Only partially. One impact of the motion in the OGC-NA for OGC API Common Core is that `conformance` needs to be changed to `ogc-conformance` (and eventually registered with IANA).

**Comment by cmheazel** [comment]
Recommendation - make sure the relation types are up to date, then close.

**Comment by cportele** [comment]
I am starting to have second thoughts on the decision to register link relation types that are purely OGC API specific with IANA and start with a "ogc-" prefix. If we do this for all the link relation types that we are going to define, then this is probably not helpful to the wider community and the long list of OGC-specific types would look more like spam. Maybe we should define (short) URIs, register them in the definitions server and use those. This is consistent with the RFC 8288 (https://tools.ietf.org/html/rfc8288#section-2.1.2) and would avoid spamming the IANA register.

**Comment by joanma747** [comment]
This will be discussed in the NA about that in 2 weeks.

Implications are:
"Applications that don't wish to register a relation type can use an extension relation type, **which is a URI** [RFC3986] that uniquely identifies the relation type. "
"... all-lowercase URIs SHOULD be used for extension relations."
"A serialisation of links can specify that they are expressed in another form, as long as they can be converted to URIs"

JM: So we could use "ogc:data" because this can be converted into a URI but we could prefer to be more specific and use a full URI.

What for the NA to decide.

**Comment by ghobona** [comment]
Link Relation Type Register has been published at https://www.opengis.net/def/rel/
